"""Assemble reports/benchmarks.md from the JSON results (numbers are never hand-edited).

    python -m src.training.report
"""
from __future__ import annotations

import json

from src.utils.config import REPORTS


def _load(name: str) -> dict | None:
    p = REPORTS / name
    return json.loads(p.read_text()) if p.exists() else None


def _row(name: str, m: dict | None, ew: dict | None = None) -> str:
    if not m:
        return f"| {name} | - | - | - | - | - | - |"
    ewr = ew.get("early_warning_recall") if ew else None
    pr = "-" if m.get("pr_auc") is None else f"{m['pr_auc']:.3f}"
    return (f"| {name} | {m['precision']:.3f} | {m['recall']:.3f} | {m['f1']:.3f} | {m['fpr']:.5f} | {pr} | "
            f"{'-' if ewr is None else f'{ewr:.1%}'} |")


HDR = ["| model | precision | recall | F1 | FPR | PR-AUC | early-warning recall |",
       "|---|---|---|---|---|---|---|"]


def main() -> None:
    wm, bl, ng, xd = _load("wm_main.json"), _load("baseline_main.json"), _load("wm_nognn.json"), \
        _load("cross_dataset.json")
    L = ["# Benchmarks", "",
         "Generated by `python -m src.training.report` from `reports/*.json`. Target: *does this host take part "
         "in attack activity at any point in the next 300 s* (5 x 60 s windows), evaluated per host and window "
         "on the held-out **test** blocks. The threshold is chosen on the validation blocks only. "
         "\"Early-warning recall\" covers only sequences whose 10-minute history is fully benign while an attack "
         "starts inside the horizon, i.e. true *prediction before onset*.", ""]
    if wm and bl:
        L += ["## 1. World model vs baselines (all training datasets pooled)", ""] + HDR + [
            _row("World model (RSSM-lite + GraphSAGE)", wm["test"]["forecast_300s"], wm["test"]["early_warning"]),
            _row("Logistic regression (same features)", bl["logreg"]["forecast_300s"], bl["logreg"]["early_warning"]),
            _row("Persistence *(oracle: uses the true current label)*", bl["persistence"]["forecast_300s"],
                 bl["persistence"]["early_warning"]),
            "", f"World-model detection of the *current* window (posterior risk head): "
                f"F1 {wm['test']['detection_now']['f1']:.3f}, PR-AUC {wm['test']['detection_now']['pr_auc']:.3f}.",
            "", "## 2. Per dataset (test blocks)", ""]
        for d, m in wm["test_per_dataset"].items():
            if not m["forecast_300s"]["positives"]:
                L += [f"**{d}**: no attack windows fall in the test blocks (all attacks of this capture are in "
                      "train/val blocks) - not scoreable.", ""]
                continue
            b = bl["test_per_dataset"].get(d, {})
            L += [f"**{d}** ({m['forecast_300s']['positives']:,} positive / {m['forecast_300s']['n']:,} sequences)",
                  ""] + HDR + [_row("World model", m["forecast_300s"], m["early_warning"]),
                               _row("Logistic regression", b.get("logreg")),
                               _row("Persistence (oracle)", b.get("persistence")), ""]
    if wm and ng:
        L += ["## 3. GNN ablation (Phase 5)", "", "| variant | F1 | PR-AUC | CIC-2017 PR-AUC | CTU-13 PR-AUC |",
              "|---|---|---|---|---|"]
        for name, r in (("with GraphSAGE host context", wm), ("without GNN", ng)):
            f = r["test"]["forecast_300s"]
            pd_ = r["test_per_dataset"]
            L.append(f"| {name} | {f['f1']:.3f} | {f['pr_auc']:.3f} | "
                     f"{pd_.get('cic2017', {}).get('forecast_300s', {}).get('pr_auc') or '-'} | "
                     f"{pd_.get('ctu13', {}).get('forecast_300s', {}).get('pr_auc') or '-'} |")
        L.append("")
    for xd, title in ((xd, "as trained"), (_load("cross_dataset_cn.json"), "with per-capture normalisation")):
        if not xd:
            continue
        L += [f"## 4. Cross-dataset zero-shot (Phase 6, R4) - {title}", "",
              f"Trained on {', '.join(xd['source'])} only; evaluated on every sequence of the target dataset with "
              "the source scaler and the source validation threshold, no fine-tuning.", ""]
        for tgt, r in xd["targets"].items():  # noqa: B007
            L += [f"**{xd['source'][0]}+ -> {tgt}**", ""] + HDR + [
                _row("World model", r["world_model"]["forecast_300s"], r["world_model"]["early_warning"]),
                _row("Logistic regression", r["logreg"]["forecast_300s"], r["logreg"]["early_warning"]),
                _row("Persistence (oracle)", r["persistence"]["forecast_300s"]), ""]
    if bl and bl["logreg"].get("shap_top_features"):
        L += ["## 5. Baseline SHAP (FR13) - top features", "",
              ", ".join(f"{x['label']} ({x['mean_abs_shap']:.2f})" for x in bl["logreg"]["shap_top_features"][:8]),
              ""]
    (REPORTS / "benchmarks.md").write_text("\n".join(L), encoding="utf-8")
    print("\n".join(L))


if __name__ == "__main__":
    main()
